from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API_PATH = ROOT / "services" / "api"
if str(API_PATH) not in sys.path:
    sys.path.insert(0, str(API_PATH))

BASE_URL = os.getenv("BASE_URL", "http://127.0.0.1:8080")
COMPOSE_FILE = ROOT / "ops" / "podman" / "compose.yml"
SERVICES = [
    "anlagen-postgres.service",
    "anlagen-app.service",
    "anlagen-mailpit.service",
    "anlagen-caddy.service",
]
CONTAINERS = ["anlagen-caddy", "anlagen-app", "anlagen-postgres", "anlagen-mailpit"]


def run(
    cmd: list[str],
    check: bool = True,
    cwd: Path | None = None,
    capture_output: bool = False,
    input_text: str | None = None,
) -> subprocess.CompletedProcess:
    print("+", " ".join(cmd))
    return subprocess.run(
        cmd,
        check=check,
        cwd=str(cwd or ROOT),
        text=True,
        capture_output=capture_output,
        input=input_text,
    )


def podman_compose(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    return run(["podman", "compose", "-f", str(COMPOSE_FILE), *args], check=check)


def ssh(cmd: str, check: bool = True, capture_output: bool = False) -> subprocess.CompletedProcess:
    return run(["podman", "machine", "ssh", cmd], check=check, capture_output=capture_output)


def to_machine_path(path: Path) -> str:
    resolved = path.resolve()
    if os.name != "nt":
        return resolved.as_posix()
    drive = resolved.drive.rstrip(":").lower()
    posix = resolved.as_posix()
    tail = posix.split(":", 1)[1] if ":" in posix else posix
    if drive:
        return f"/mnt/{drive}{tail}"
    return tail


def ensure_machine_running() -> None:
    res = run(["podman", "machine", "start"], check=False, capture_output=True)
    err = (res.stderr or "").strip()
    if res.returncode != 0 and "already running" not in err.lower():
        raise SystemExit(f"podman machine start failed: {err or res.stdout}")


def ensure_machine_dirs() -> None:
    ssh(
        "sudo mkdir -p /srv/anlagenserver/pgdata /srv/anlagenserver/files /srv/anlagenserver/reports "
        "/srv/anlagenserver/logs /srv/anlagenserver/backups /srv/anlagenserver/config /etc/containers/systemd && "
        "sudo chmod -R 777 /srv/anlagenserver"
    )


def install_quadlets() -> None:
    root_vm = to_machine_path(ROOT)
    ssh(f"sudo cp {root_vm}/ops/podman/quadlet/*.container /etc/containers/systemd/")
    ssh(f"sudo cp {root_vm}/ops/caddy/Caddyfile /srv/anlagenserver/config/Caddyfile")
    ssh(f"sudo cp {root_vm}/ops/podman/env/app.env /srv/anlagenserver/config/app.env")
    ssh(f"sudo cp {root_vm}/ops/podman/env/postgres.env /srv/anlagenserver/config/postgres.env")
    ssh("sudo podman network exists anlagen-net || sudo podman network create anlagen-net")


def build_app_image_rootful() -> None:
    root_vm = to_machine_path(ROOT)
    ssh(f"cd {root_vm} && sudo podman build -f services/api/Dockerfile -t localhost/anlagen-app:latest .")


def start_quadlet_services() -> None:
    joined = " ".join(SERVICES)
    ssh("sudo systemctl daemon-reload")
    ssh(f"sudo systemctl stop {joined}", check=False)
    ssh(f"sudo systemctl start {joined}")


def stop_quadlet_services() -> None:
    joined = " ".join(SERVICES)
    ssh(f"sudo systemctl stop {joined}", check=False)


def remove_local_named_containers() -> None:
    run(["podman", "rm", "-f", *CONTAINERS], check=False)


def quadlet_app_active() -> bool:
    res = ssh("sudo systemctl is-active anlagen-app.service", check=False, capture_output=True)
    return res.returncode == 0 and res.stdout.strip() == "active"


def _generate_schema_via_image() -> str | None:
    code = (
        "from sqlalchemy.schema import CreateTable; "
        "from app.db.models import Base; "
        "from app.db.session import engine; "
        "d=engine.dialect; "
        "print('-- generated by tools/sb_agent.py'); "
        "print('-- source: SQLAlchemy metadata'); "
        "print(); "
        "[print(str(CreateTable(t).compile(dialect=d)).rstrip() + ';\\n') for t in Base.metadata.sorted_tables]"
    )
    local = run(
        ["podman", "run", "--rm", "localhost/anlagen-app:latest", "python", "-c", code],
        check=False,
        capture_output=True,
    )
    if local.returncode == 0 and local.stdout.strip():
        return local.stdout

    remote = ssh(
        f"sudo podman run --rm localhost/anlagen-app:latest python -c {shlex.quote(code)}",
        check=False,
        capture_output=True,
    )
    if remote.returncode == 0 and remote.stdout.strip():
        return remote.stdout
    return None


def generate_db_schema() -> None:
    out = ROOT / "docs" / "db_schema.sql"
    try:
        from sqlalchemy.schema import CreateTable
        from app.db.models import Base
        from app.db.session import engine
    except ModuleNotFoundError:
        via_image = _generate_schema_via_image()
        if via_image:
            out.write_text(via_image, encoding="utf-8")
            print(f"wrote {out} (from container image)")
            return
        out.write_text("-- dependencies missing on host; schema generation failed\n", encoding="utf-8")
        print(f"wrote {out} (placeholder)")
        return

    lines = [
        "-- generated by tools/sb_agent.py",
        "-- source: SQLAlchemy metadata",
        "",
    ]
    dialect = engine.dialect
    for table in Base.metadata.sorted_tables:
        ddl = str(CreateTable(table).compile(dialect=dialect)).rstrip()
        lines.append(f"{ddl};")
        lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


def cmd_up() -> None:
    ensure_machine_running()
    ensure_machine_dirs()
    build_app_image_rootful()
    generate_db_schema()
    install_quadlets()
    remove_local_named_containers()
    start_quadlet_services()
    wait_ready()


def cmd_down() -> None:
    stop_quadlet_services()
    remove_local_named_containers()
    podman_compose("down", check=False)


def cmd_seed() -> None:
    code = (
        "from app.db.session import SessionLocal; "
        "from app.seed_data import seed; "
        "db=SessionLocal(); seed(db); db.close(); print('seed complete')"
    )
    if quadlet_app_active():
        ssh(f"sudo podman exec anlagen-app python -c {shlex.quote(code)}")
        return
    run(["podman", "exec", "anlagen-app", "python", "-c", code])


def wait_ready(timeout_seconds: int = 180) -> None:
    import urllib.request

    deadline = time.time() + timeout_seconds
    last_error = ""
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(f"{BASE_URL}/readyz", timeout=5) as resp:
                if resp.status == 200:
                    print("stack is ready")
                    return
        except Exception as exc:  # pragma: no cover
            last_error = str(exc)
        time.sleep(2)
    raise SystemExit(f"timeout waiting for readyz: {last_error}")


def cmd_smoke() -> None:
    run([sys.executable, str(ROOT / "services" / "api" / "tests_smoke" / "smoke_http.py")])


def ensure_host_python_deps() -> None:
    try:
        import pytest  # noqa: F401
    except Exception:
        run([sys.executable, "-m", "pip", "install", "-r", str(ROOT / "services" / "api" / "requirements.txt")])


def cmd_test() -> None:
    if quadlet_app_active():
        tests_vm = f"{to_machine_path(ROOT)}/tests/."
        ssh("sudo podman exec anlagen-app sh -lc 'rm -rf /app/tests && mkdir -p /app/tests'")
        ssh(f"sudo podman cp {shlex.quote(tests_vm)} anlagen-app:/app/tests")
        ssh(
            "sudo podman exec --env PYTHONPATH=/app/tests/api --env BASE_URL=http://anlagen-caddy:8080 "
            "anlagen-app python -m pytest /app/tests/api -q"
        )
    else:
        run(["podman", "exec", "anlagen-app", "sh", "-lc", "rm -rf /app/tests && mkdir -p /app/tests"])
        run(["podman", "cp", str(ROOT / "tests") + "/.", "anlagen-app:/app/tests"])
        run(
            [
                "podman",
                "exec",
                "--env",
                "PYTHONPATH=/app/tests/api",
                "--env",
                "BASE_URL=http://anlagen-caddy:8080",
                "anlagen-app",
                "python",
                "-m",
                "pytest",
                "/app/tests/api",
                "-q",
            ]
        )

    ui_dir = ROOT / "tests" / "ui"
    npm_cmd = "npm.cmd" if os.name == "nt" else "npm"
    npx_cmd = "npx.cmd" if os.name == "nt" else "npx"

    try:
        run([npm_cmd, "install"], cwd=ui_dir)
        run([npx_cmd, "playwright", "install", "chromium"], cwd=ui_dir)
        run([npx_cmd, "playwright", "test"], cwd=ui_dir)
    except Exception as exc:
        raise SystemExit(f"ui tests failed: {exc}")


def cmd_bundle() -> None:
    run(["podman", "exec", "anlagen-app", "python", "-c", "print('bundle handled via /api/ops/logs/download?days=7')"])


def main() -> None:
    parser = argparse.ArgumentParser(description="Anlagenbuch stack helper")
    parser.add_argument("command", choices=["up", "down", "seed", "smoke", "test", "bundle", "schema"])
    args = parser.parse_args()

    if args.command == "up":
        cmd_up()
    elif args.command == "down":
        cmd_down()
    elif args.command == "seed":
        cmd_seed()
    elif args.command == "smoke":
        cmd_smoke()
    elif args.command == "test":
        cmd_test()
    elif args.command == "bundle":
        cmd_bundle()
    elif args.command == "schema":
        generate_db_schema()


if __name__ == "__main__":
    main()
