-- generated by tools/sb_agent.py
-- source: SQLAlchemy metadata


CREATE TABLE areas (
	id SERIAL NOT NULL, 
	code VARCHAR(16) NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (code)
);


CREATE TABLE dead_letter_deliveries (
	id SERIAL NOT NULL, 
	delivery_id INTEGER NOT NULL, 
	target VARCHAR(300) NOT NULL, 
	payload JSON NOT NULL, 
	last_error TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);


CREATE TABLE files (
	id SERIAL NOT NULL, 
	storage_name VARCHAR(255) NOT NULL, 
	filename_original VARCHAR(255) NOT NULL, 
	mime VARCHAR(120) NOT NULL, 
	size_bytes INTEGER NOT NULL, 
	sha256 VARCHAR(64) NOT NULL, 
	path VARCHAR(500) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (storage_name)
);


CREATE TABLE idempotency_keys (
	id SERIAL NOT NULL, 
	key VARCHAR(120) NOT NULL, 
	scope VARCHAR(120) NOT NULL, 
	response_body TEXT NOT NULL, 
	status_code INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (key)
);


CREATE TABLE ops_error_index (
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	route VARCHAR(255) NOT NULL, 
	trace_id VARCHAR(64) NOT NULL, 
	exception_type VARCHAR(120) NOT NULL, 
	message TEXT NOT NULL, 
	file_ref VARCHAR(255) NOT NULL, 
	status_code INTEGER NOT NULL, 
	PRIMARY KEY (id)
);


CREATE TABLE ops_health_snapshots (
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	db_ok BOOLEAN NOT NULL, 
	disk_ok BOOLEAN NOT NULL, 
	backlog INTEGER NOT NULL, 
	response_ms INTEGER NOT NULL, 
	last_error TEXT, 
	PRIMARY KEY (id)
);


CREATE TABLE outbox_events (
	id SERIAL NOT NULL, 
	aggregate_type VARCHAR(60) NOT NULL, 
	aggregate_id INTEGER NOT NULL, 
	event_type VARCHAR(120) NOT NULL, 
	payload JSON NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	published_at TIMESTAMP WITH TIME ZONE, 
	attempts INTEGER NOT NULL, 
	last_error TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);


CREATE TABLE permissions (
	id SERIAL NOT NULL, 
	code VARCHAR(120) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (code)
);


CREATE TABLE plants (
	id SERIAL NOT NULL, 
	slug VARCHAR(120) NOT NULL, 
	display_name VARCHAR(255) NOT NULL, 
	area_prefix VARCHAR(8) NOT NULL, 
	active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);


CREATE TABLE report_runs (
	id SERIAL NOT NULL, 
	requested_by VARCHAR(120) NOT NULL, 
	plant_slug VARCHAR(120) NOT NULL, 
	range_from TIMESTAMP WITH TIME ZONE, 
	range_to TIMESTAMP WITH TIME ZONE, 
	status VARCHAR(32) NOT NULL, 
	error_message TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);


CREATE TABLE report_schedules (
	id SERIAL NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	cron_type VARCHAR(16) NOT NULL, 
	timezone VARCHAR(64) NOT NULL, 
	plant_slug VARCHAR(120) NOT NULL, 
	formats_json JSON NOT NULL, 
	recipients_json JSON NOT NULL, 
	enabled BOOLEAN NOT NULL, 
	last_run_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);


CREATE TABLE roles (
	id SERIAL NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name)
);


CREATE TABLE users (
	id SERIAL NOT NULL, 
	username VARCHAR(120) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	force_password_change BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);


CREATE TABLE deliveries (
	id SERIAL NOT NULL, 
	outbox_event_id INTEGER NOT NULL, 
	target VARCHAR(300) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	attempts INTEGER NOT NULL, 
	last_error TEXT, 
	next_retry_at TIMESTAMP WITH TIME ZONE, 
	last_attempt_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(outbox_event_id) REFERENCES outbox_events (id) ON DELETE CASCADE
);


CREATE TABLE file_links (
	id SERIAL NOT NULL, 
	file_id INTEGER NOT NULL, 
	scope_type VARCHAR(60) NOT NULL, 
	scope_id INTEGER NOT NULL, 
	kind VARCHAR(60) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(file_id) REFERENCES files (id) ON DELETE CASCADE
);


CREATE TABLE report_artifacts (
	id SERIAL NOT NULL, 
	report_run_id INTEGER NOT NULL, 
	format VARCHAR(16) NOT NULL, 
	mime_type VARCHAR(120) NOT NULL, 
	path VARCHAR(500) NOT NULL, 
	size_bytes INTEGER NOT NULL, 
	sha256 VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(report_run_id) REFERENCES report_runs (id) ON DELETE CASCADE
);


CREATE TABLE report_deliveries (
	id SERIAL NOT NULL, 
	report_run_id INTEGER NOT NULL, 
	recipient VARCHAR(255) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	attempts INTEGER NOT NULL, 
	last_error TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(report_run_id) REFERENCES report_runs (id) ON DELETE CASCADE
);


CREATE TABLE role_permissions (
	id SERIAL NOT NULL, 
	role_id INTEGER NOT NULL, 
	permission_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id), 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE, 
	FOREIGN KEY(permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);


CREATE TABLE shift_entries (
	id SERIAL NOT NULL, 
	plant_id INTEGER NOT NULL, 
	author_name VARCHAR(200) NOT NULL, 
	author_token_hash VARCHAR(128) NOT NULL, 
	subject VARCHAR(300) NOT NULL, 
	body TEXT NOT NULL, 
	status VARCHAR(60) NOT NULL, 
	shift_id VARCHAR(64) NOT NULL, 
	editable_until TIMESTAMP WITH TIME ZONE NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(plant_id) REFERENCES plants (id)
);


CREATE TABLE tickets (
	id SERIAL NOT NULL, 
	plant_id INTEGER NOT NULL, 
	requester_name VARCHAR(200) NOT NULL, 
	subject VARCHAR(300) NOT NULL, 
	description TEXT NOT NULL, 
	status VARCHAR(60) NOT NULL, 
	department VARCHAR(120), 
	priority_rank INTEGER, 
	ticket_type VARCHAR(120), 
	area VARCHAR(16) NOT NULL, 
	assignee_user_id INTEGER, 
	wrong_plant_reason VARCHAR(120), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(plant_id) REFERENCES plants (id), 
	FOREIGN KEY(assignee_user_id) REFERENCES users (id)
);


CREATE TABLE user_roles (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	role_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_user_role UNIQUE (user_id, role_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE
);


CREATE TABLE shift_entry_events (
	id SERIAL NOT NULL, 
	entry_id INTEGER NOT NULL, 
	event_type VARCHAR(120) NOT NULL, 
	event_payload JSON NOT NULL, 
	actor_ref VARCHAR(255) NOT NULL, 
	prev_hash VARCHAR(64) NOT NULL, 
	hash VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(entry_id) REFERENCES shift_entries (id) ON DELETE CASCADE
);


CREATE TABLE ticket_assignments (
	id SERIAL NOT NULL, 
	ticket_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	assigned_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(ticket_id) REFERENCES tickets (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id)
);


CREATE TABLE ticket_events (
	id SERIAL NOT NULL, 
	ticket_id INTEGER NOT NULL, 
	event_type VARCHAR(120) NOT NULL, 
	event_payload JSON NOT NULL, 
	actor_ref VARCHAR(255) NOT NULL, 
	is_public BOOLEAN NOT NULL, 
	prev_hash VARCHAR(64) NOT NULL, 
	hash VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(ticket_id) REFERENCES tickets (id) ON DELETE CASCADE
);


CREATE TABLE ticket_public_tokens (
	id SERIAL NOT NULL, 
	ticket_id INTEGER NOT NULL, 
	token_hash VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (ticket_id), 
	FOREIGN KEY(ticket_id) REFERENCES tickets (id) ON DELETE CASCADE
);

